### ISSUE TITLE
Can't build on current Arch

### ISSUE THREAD

**Issue by ato2** [CachyOS/New-Cli-Installer#12]
[ 16%] Building CXX object _deps/ftxui-build/CMakeFiles/screen.dir/src/ftxui/screen/screen.cpp.o
[ 16%] Building CXX object _deps/ftxui-build/CMakeFiles/screen.dir/src/ftxui/screen/string.cpp.o
/tmp/new-cli-installer/build/_deps/ftxui-src/src/ftxui/screen/string.cpp: In function ‘int ftxui::wchar_width(wchar_t)’:
/tmp/new-cli-installer/build/_deps/ftxui-src/src/ftxui/screen/string.cpp:247:19: error: function might be candidate for attribute ‘const’ [-Werror=suggest-attribute=const]
  247 | [[gnu::pure]] int wchar_width(wchar_t ucs) {
      |                   ^~~~~~~~~~~

**Comment by vnepogodin** [comment]
looks like it was fixed, because I cannot reproduce it on CI and locally
