### ISSUE TITLE
Can't boot with zfs partition

### ISSUE THREAD

**Issue by Pinghigh** [CachyOS/New-Cli-Installer#5]
My system cannot boot with zfs root partition.

I have tried every bootloader but it doesn't work.

**Comment by ptr1337** [comment]
Did you tested the latest GUI ISO? There is also the CLI Installer installed. 

The current CLI ISO, needs a update of the CLI installer itself, to make ZFS working correctly. We will push a new one the next days.

**Comment by Pinghigh** [comment]
> Did you tested the latest GUI ISO? There is also the CLI Installer installed.
> 
> The current CLI ISO, needs a update of the CLI installer itself, to make ZFS working correctly. We will push a new one the next days.

i think it's not an issue with zfs but with bootloaders
(because of zfs module, i installed cachyos with GUI ISO)
grub tells that "unknown filesystem"
systemd-boot didn't create an EFI file
rEFind didn't find my root partition with zfs_zstd

and now i'm using zfsbootmenu configured by [eoli3n](https://github.com/eoli3n) with some changes by myself
here is [the address](https://github.com/eoli3n/arch-config)

(English is not my first language)

**Comment by ptr1337** [comment]
I just tested a installation with the Calamares GUI Installer with systemd-boot and also the CLI-Installer (using the GUI ISO and starting the TUI with grub Installer with` sudo cachyos-installer`.

Both has been correctly installed. And booted fine in a qemu with UEFI.

**Comment by ptr1337** [comment]
Mhm, just noticed when booting this issue. I will have a closer look into this, thanks

**Comment by ptr1337** [comment]
> > Did you tested the latest GUI ISO? There is also the CLI Installer installed.
> > The current CLI ISO, needs a update of the CLI installer itself, to make ZFS working correctly. We will push a new one the next days.
> 
> i think it's not an issue with zfs but with bootloaders (because of zfs module, i installed cachyos with GUI ISO) grub tells that "unknown filesystem" systemd-boot didn't create an EFI file rEFind didn't find my root partition with zfs_zstd
> 
> and now i'm using zfsbootmenu configured by [eoli3n](https://github.com/eoli3n) with some changes by myself here is [the address](https://github.com/eoli3n/arch-config)
> 
> (English is not my first language)

I was able to cherry pick calamares, which commit is causing this. It seems like the latest commit from dalto8 with the zfshostid implementation is breaking our calamares.

I will revert these commits and will push a new calamares packages into our repo, then it will be fixed.

The CLI Iso just needs to be updated, as I wrote above. In the latest CLI ISO, is a issue at the mkinitcpio.cfg zfs module, and is already fixed from us

**Comment by Pinghigh** [comment]
Will booting with grub/sysdemd-boot from zfs(zstd compression) root partition come true?

**Comment by vnepogodin** [comment]
Closing this one!
